# Inspired from https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
name: GitHub Pages

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - id: configurepages
        uses: actions/configure-pages@v5
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npm install

       # New step: Debug environment variables
      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables:"
          echo "NEXT_PUBLIC_GISCUS_REPO is set: ${{ secrets.NEXT_PUBLIC_GISCUS_REPO != '' }}"
          echo "NEXT_PUBLIC_GISCUS_REPOSITORY_ID is set: ${{ secrets.NEXT_PUBLIC_GISCUS_REPOSITORY_ID != '' }}"
          echo "NEXT_PUBLIC_GISCUS_CATEGORY is set: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY != '' }}"
          echo "NEXT_PUBLIC_GISCUS_CATEGORY_ID is set: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY_ID != '' }}"
          echo "NEXT_UMAMI_ID is set: ${{ secrets.NEXT_UMAMI_ID  != '' }}"
          echo "NEXT_UMAMI_WEBSITE_ID is set: ${{ secrets.NEXT_UMAMI_WEBSITE_ID  != '' }}"
          
          # Log the variables without exposing their values
          if [ -n "$NEXT_PUBLIC_GISCUS_REPO" ]; then echo "NEXT_PUBLIC_GISCUS_REPO is non-empty"; else echo "NEXT_PUBLIC_GISCUS_REPO is empty"; fi
          if [ -n "$NEXT_PUBLIC_GISCUS_REPOSITORY_ID" ]; then echo "NEXT_PUBLIC_GISCUS_REPOSITORY_ID is non-empty"; else echo "NEXT_PUBLIC_GISCUS_REPOSITORY_ID is empty"; fi
          if [ -n "$NEXT_PUBLIC_GISCUS_CATEGORY" ]; then echo "NEXT_PUBLIC_GISCUS_CATEGORY is non-empty"; else echo "NEXT_PUBLIC_GISCUS_CATEGORY is empty"; fi
          if [ -n "$NEXT_PUBLIC_GISCUS_CATEGORY_ID" ]; then echo "NEXT_PUBLIC_GISCUS_CATEGORY_ID is non-empty"; else echo "NEXT_PUBLIC_GISCUS_CATEGORY_ID is empty"; fi
          if [ -n "$NEXT_UMAMI_ID" ]; then echo "NEXT_UMAMI_ID is non-empty"; else echo "NEXT_UMAMI_ID is empty"; fi
          if [ -n "$NEXT_UMAMI_WEBSITE_ID" ]; then echo "NEXT_UMAMI_WEBSITE_ID is non-empty"; else echo "NEXT_UMAMI_WEBSITE_ID is empty"; fi
        env:
          NEXT_PUBLIC_GISCUS_REPO: ${{ secrets.NEXT_PUBLIC_GISCUS_REPO }}
          NEXT_PUBLIC_GISCUS_REPOSITORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_REPOSITORY_ID }}
          NEXT_PUBLIC_GISCUS_CATEGORY: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY }}
          NEXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY_ID }}
          NEXT_UMAMI_ID:  ${{ secrets.NEXT_UMAMI_ID }}
          NEXT_UMAMI_WEBSITE_ID:  ${{ secrets.NEXT_UMAMI_WEBSITE_ID }}
          
      - run: npm run build
        env:
          EXPORT: 1
          UNOPTIMIZED: 1
          BASE_PATH: ${{ steps.configurepages.outputs.base_path }}
          NEXT_PUBLIC_GISCUS_REPO: ${{ secrets.NEXT_PUBLIC_GISCUS_REPO }}
          NEXT_PUBLIC_GISCUS_REPOSITORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_REPOSITORY_ID }}
          NEXT_PUBLIC_GISCUS_CATEGORY: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY }}
          NEXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY_ID }}
          NEXT_UMAMI_ID:  ${{ secrets.NEXT_UMAMI_ID }}
          NEXT_UMAMI_WEBSITE_ID:  ${{ secrets.NEXT_UMAMI_WEBSITE_ID }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
